version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Apt
          command: |
            apt install -y bzip2 clang
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
