version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Apt
          command: |
            apt update
            apt install -y build-essential bzip2 clang cmake
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
