refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
  - stdout
loggers:
  ahghee::shard::tests:
    level: debug
  app::requests:
    level: info
    appenders:
    - requests
    additive: false