# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest
        # todo: , macos-latest
        ]
    
    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: 3.1.201 
    - name: Ubuntu Dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install libc6-dev libsnappy-dev

    - name: Macos Dependencies
      if: ${{ matrix.os == 'macos-latest' }}
      run:

    - name: Test
      run: cd src; dotnet test ./core.tests/
